<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var common\models\RbacAuthItem $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('app', 'RbacAuthItem');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'RbacAuthItems'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'name' => $model->name]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud rbac-auth-item-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Yii::t('app', 'RbacAuthItem') ?>        <small>
            <?= $model->name ?>        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?= Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit',
            [ 'update', 'name' => $model->name],
            ['class' => 'btn btn-info']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . 'Copy',
            ['create', 'name' => $model->name, 'RbacAuthItem'=>$copyParams],
            ['class' => 'btn btn-success']) ?>

            <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New',
            ['create'],
            ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr />

    <?php $this->beginBlock('common\models\RbacAuthItem'); ?>

    
    <?= DetailView::widget([
    'model' => $model,
    'attributes' => [
            'name',
        'type',
        'description:ntext',
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'rule_name',
    'value' => ($model->getRuleName()->one() ? Html::a($model->getRuleName()->one()->name, ['rbac-auth-rule/view', 'name' => $model->getRuleName()->one()->name,]) : '<span class="label label-warning">?</span>'),
],
        'data:ntext',
        'created_at',
        'updated_at',
    ],
    ]); ?>

    
    <hr/>

    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'name' => $model->name],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]); ?>
    <?php $this->endBlock(); ?>


    
<?php $this->beginBlock('RbacAuthAssignments'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Rbac Auth Assignments',
            ['rbac-auth-assignment/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Rbac Auth Assignment',
            ['rbac-auth-assignment/create', 'RbacAuthAssignment' => ['item_name' => $model->name]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-RbacAuthAssignments', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-RbacAuthAssignments ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getRbacAuthAssignments(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-rbacauthassignments']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'rbac-auth-assignment' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'rbac-auth-assignment'
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'user_id',
    'value' => function ($model) {
        if ($rel = $model->getUser()->one()) {
            return Html::a($rel->id, ['user/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'created_at',
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('RbacAuthItemChildrens'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Rbac Auth Item Childrens',
            ['rbac-auth-item-child/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Rbac Auth Item Children',
            ['rbac-auth-item-child/create', 'RbacAuthItemChild' => ['parent' => $model->name]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-RbacAuthItemChildrens', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-RbacAuthItemChildrens ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getRbacAuthItemChildrens(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-rbacauthitemchildrens']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'rbac-auth-item-child' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'rbac-auth-item-child'
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'child',
    'value' => function ($model) {
        if ($rel = $model->getChild()->one()) {
            return Html::a($rel->name, ['rbac-auth-item/view', 'name' => $rel->name,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('RbacAuthItemChildren0s'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Rbac Auth Item Children0s',
            ['rbac-auth-item-child/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Rbac Auth Item Children0',
            ['rbac-auth-item-child/create', 'RbacAuthItemChild' => ['child' => $model->name]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-RbacAuthItemChildren0s', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-RbacAuthItemChildren0s ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getRbacAuthItemChildrens(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-rbacauthitemchildren0s']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'rbac-auth-item-child' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'rbac-auth-item-child'
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'parent',
    'value' => function ($model) {
        if ($rel = $model->getParent()->one()) {
            return Html::a($rel->name, ['rbac-auth-item/view', 'name' => $rel->name,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('Childrens'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Childrens',
            ['rbac-auth-item/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Children',
            ['rbac-auth-item/create', 'RbacAuthItem' => ['name' => $model->name]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-link"></span> ' . 'Attach' . ' Children', ['rbac-auth-item-child/create', 'RbacAuthItemChild'=>['parent'=>$model->name]],
            ['class'=>'btn btn-info btn-xs']
        ) ?>
</div></div><?php Pjax::begin(['id'=>'pjax-Childrens', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Childrens ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getRbacAuthItemChildren(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-rbacauthitemchildren']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'rbac-auth-item-child' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'rbac-auth-item-child'
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'child',
    'value' => function ($model) {
        if ($rel = $model->getChild()->one()) {
            return Html::a($rel->name, ['rbac-auth-item/view', 'name' => $rel->name,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


<?php $this->beginBlock('Parents'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Parents',
            ['rbac-auth-item/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Parent',
            ['rbac-auth-item/create', 'RbacAuthItem' => ['name' => $model->name]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-link"></span> ' . 'Attach' . ' Parent', ['rbac-auth-item-child/create', 'RbacAuthItemChild'=>['parent'=>$model->name]],
            ['class'=>'btn btn-info btn-xs']
        ) ?>
</div></div><?php Pjax::begin(['id'=>'pjax-Parents', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Parents ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">' . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider(['query' => $model->getRbacAuthItemChildren(), 'pagination' => ['pageSize' => 20, 'pageParam'=>'page-rbacauthitemchildren']]),
    'pager'        => [
        'class'          => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [[
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'rbac-auth-item-child' . '/' . $action;
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'rbac-auth-item-child'
],
// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'child',
    'value' => function ($model) {
        if ($rel = $model->getChild()->one()) {
            return Html::a($rel->name, ['rbac-auth-item/view', 'name' => $rel->name,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
]
]) . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


    <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->name.'</b>',
    'content' => $this->blocks['common\models\RbacAuthItem'],
    'active'  => true,
],[
    'content' => $this->blocks['RbacAuthAssignments'],
    'label'   => '<small>Rbac Auth Assignments <span class="badge badge-default">'.count($model->getRbacAuthAssignments()->asArray()->all()).'</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['RbacAuthItemChildrens'],
    'label'   => '<small>Rbac Auth Item Childrens <span class="badge badge-default">'.count($model->getRbacAuthItemChildrens()->asArray()->all()).'</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['RbacAuthItemChildren0s'],
    'label'   => '<small>Rbac Auth Item Children0s <span class="badge badge-default">'.count($model->getRbacAuthItemChildrens()->asArray()->all()).'</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['Childrens'],
    'label'   => '<small>Childrens <span class="badge badge-default">'.count($model->getChildrens()->asArray()->all()).'</span></small>',
    'active'  => false,
],[
    'content' => $this->blocks['Parents'],
    'label'   => '<small>Parents <span class="badge badge-default">'.count($model->getParents()->asArray()->all()).'</span></small>',
    'active'  => false,
], ]
                 ]
    );
    ?>
</div>
